#!/bin/sh
set -x

DOCSY_DIR = "themes/docsy"
if [ ! -d "$DOCSY_DIR" ]; then
  git clone --recurse-submodules --depth 1 https://github.com/google/docsy.git $DOCSY_DIR
fi


cd $1
npm install -D --save autoprefixer
npm install -D --save postcss-cli
